name: workflow
on: push
jobs:
    dependencies:
      name: dependincies
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: yarn install
    build:
      name: build
      runs-on: ubuntu-latest
      needs: dependencies
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 22.11.0
              cache: 'yarn'
          - run: yarn install
          - run: yarn run build
    linters:
        name: lint
        runs-on: ubuntu-latest
        needs: dependencies
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 22.11.0
              cache: 'yarn'
          - run: yarn install
          - run: yarn run linters
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        needs: linters
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-node@v4
            with:
              node-version: 22.11.0
              cache: 'yarn'
          - run: yarn install
          - run: yarn run deploy
